#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20

xv=1
while [ $xv -le 20 ]; do
	echo "$xv"
	case $xv in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( xv++ ))
done
